### ISSUE TITLE
Camunda on subfolder 

### ISSUE THREAD

**Issue by hodjaev** [camunda-community-hub/camunda-helm#23]
Hello. 
In the values.yaml file if I write ingress section like this it works
```
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: camunda-bpm-platform.local
      paths:
        - /
```
But if I change path to, for example, /bpm it isn't working.

```
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: camunda-bpm-platform.local
      paths:
        - /bpm
```

![image](https://user-images.githubusercontent.com/69766846/140754990-68f26f2e-cfcf-4d40-a8ac-ee3c9a412acb.png)

**Comment by aabouzaid** [comment]
Hi @hodjaev this is not related to the Camunda Platform, it's related to Ingress rewrite.

Try this (this is untested, just from top of my mind, also depends on your ingress version):
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-camunda-bpm-platform
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
spec:
  rules:
  - host: cambpm.kubernetes.example
    http:
      paths:
      - backend:
          serviceName: demo-camunda-bpm-platform
          servicePort: 8080
        path: /bpm(/|$)(.*)
```
