### ISSUE TITLE
deployment.yaml bug in args

### ISSUE THREAD

**Issue by ricardofmsimoes** [camunda-community-hub/camunda-helm#28]
Hi guys

I was trying to use the helm to deploy camunda with rest and webapps only but it wasn't working.
I was not able to set camunda running.

In _image_ section I try things like
```
image:
  name: camunda/camunda-bpm-platform
  tag: run-latest
  command: ["./camunda.sh"]
  args:
   - --rest
   - --webapps
```

OR
```
image:
  name: camunda/camunda-bpm-platform
  tag: run-latest
  command: ["./camunda.sh"]
  args: [--rest, --webapps]
```

Or Even 
```
image:
  name: camunda/camunda-bpm-platform
  tag: run-latest
  command: ["./camunda.sh"]
  args: ["--rest", "--webapps" ]
```

Nothing work, in the "final deployment YAML file" the args always become:
```
args:
  - '--rest --webapps'
```

I started looking into _camunda.sh_ and _start.sh_ file and I figureout the reason for the camunda not start.
The _'--rest --webapps'_ is interpreted as one arg and not as 2 args.

After a long days trying to find the reason for that args are not being interpreted as  2 args I found an issue on the deployment.yaml file

Here is my conclusion, in the _args_ part in the deployment.yaml file instead of
```
{{- if .Values.image.args }}
  args: 
    {{ .Values.image.args }}
  {{- end }}
``` 
should be:
```
 {{- if .Values.image.args }}
  args: 
    {{- toYaml .Values.image.args | nindent 12 }}
  {{- end }}
```

Do you think it is possible to do this change? 
Or it will have impact in other use case ?
