### ISSUE TITLE
All beta Ingress APIs are removed in Kubernetes v1.22

### ISSUE THREAD

**Issue by gnoejuan** [camunda-community-hub/camunda-helm#33]
```yaml
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
```

Suggested action: Migrate to use the networking.k8s.io/v1 Ingress API, available since v1.19.

Source: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

**Comment by gnoejuan** [comment]
Another solution would be to follow bitnami's solution

```yaml
...
apiVersion: {{ template "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
...
```

Sources: https://github.com/bitnami/charts/blob/959769b33b27fe3dc28dbbcf2dc10b1227eab382/bitnami/harbor/templates/ingress/ingress.yaml

https://github.com/bitnami/charts/tree/master/bitnami/harbor#traffic-exposure-parameters
