### ISSUE TITLE
Can't Specify service.ports.nodePort in Service template

### ISSUE THREAD

**Issue by chrisbmoore** [camunda-community-hub/camunda-helm#34]
I'd like to expose Camunda externally to Kubernetes on a set port using a NodePort Service, but I also need a way to specify the `service.ports.nodePort` in my values.yaml. Should there be a PR to add this to the template for NodePort?

**Comment by samuelzimmermanphillips** [comment]
You used to be able to do this with the following in your values.yaml:
```
service:
  type: NodePort
  port: 80
  targetPort: 8080
  portName: http
  ```

This configuration used to work for me, however it seems like this configuration was broken some time in the last 60 or so days. Because now the pod refuses connections on any ports when you do a forward.
